project:
  type: website

website:
  title: "Frigo Vide"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: data/recipe/data_report.qmd
        text: "Data Report"
    tools:
      - icon: github
        menu:
          - text: Source Code
            href:  https://github.com/marie678/Projet-Mise-en-prod-3A.git
  back-to-top-navigation: true
  page-footer: "Copyright 2025, ENSAE Paris"
  repo-url: https://github.com/marie678/Projet-Mise-en-prod-3A.git
  repo-actions: [edit, source, issue]


format:
  html:
    theme:
      - minty
      - brand
    css: styles.css
    toc: true
