DATA_DIR: 'https://minio.lab.sspcloud.fr/mmeyer/projet-mise-en-prod/data/raw/' #'s3://mmeyer/projet-mise-en-prod/data/raw'
s3:
  endpoint_url: "https://minio.lab.sspcloud.fr"
SAMPLE_RECIPE_FILENAME: 'sample_recipes_10k2.parquet'
BASE_DIR = (os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
SAMPLE_RECIPE_PATH = os.path.join(BASE_DIR, 'Data/sample_recipes_10k2.parquet')

nutrition_data:
  file: 'recipes.parquet'
  keep_col: ['Name', 'AuthorName', 'CookTime', 'PrepTime', 'TotalTime', 'Description', 'Images', 'RecipeCategory', 'Keywords', 'AggregatedRating', 'ReviewCount', 'Calories', 'FatContent', 'SaturatedFatContent','CholesterolContent', 'SodiumContent', 'CarbohydrateContent', 'FiberContent', 'SugarContent','ProteinContent', 'RecipeServings', 'RecipeInstructions']
  to_format:  ['RecipeInstructions', 'Keywords']
  numeric_float_var: ['AggregatedRating', 'Calories','FatContent','SaturatedFatContent','CholesterolContent'
               ,'SodiumContent','CarbohydrateContent','FiberContent','SugarContent','ProteinContent']
  numeric_int_var: ['ReviewCount','RecipeServings']
  list_var: ['Images','Keywords','RecipeInstructions']

measurements_data:
  file: 'recipes_data.parquet'
  keep_col: ['title','directions','ingredients','link','NER']
  to_format: ['ingredients', 'directions', 'NER']
  list_var: ['ingredients', 'directions','NER']