name: Publish Quarto Website

on:
    push:
        branches: main

jobs:
    deploy:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout repository
              uses: actions/checkout@v3

            - name: Setup Quarto
              uses: quarto-dev/quarto-actions/setup@v2

            - name: Install Pandoc (required for Quarto)
              uses: r-lib/actions/setup-pandoc@v2

            - name: Setup Python and Install Jupyter
              uses: actions/setup-python@v4
              with:
                python-version: '3.x' # Or specify a specific Python version
            - run: python -m pip install jupyter

            - name: Render Quarto Project
              run: quarto render

            - name: Deploy to GitHub Pages
              uses: peaceiris/actions-gh-pages@v3
              with:
                github_token: ${{ secrets.GITHUB_TOKEN }}
                publish_dir: _site
